### ISSUE TITLE
Kick-Off JOSS Paper

### ISSUE THREAD

**Issue by philipplk** [philipplk/metis#11]
Hey @JulianKarlBauer ,

do you want to write a JOSS-paper on this project together?

Let me know what you think.

Best regards

**Comment by philipplk** [comment]
@JulianKarlBauer Hast du Lust mal reinzuschauen und die Struktur aufzusetzen, bzw. Dinge reinzuschreiben, die du gerne lesen würdest in so einem Paper?

**Comment by JulianKarlBauer** [comment]
See branch https://github.com/philipplk/metis/tree/11-kick-off-joss-paper

**Comment by JulianKarlBauer** [comment]
See also https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

**Comment by philipplk** [comment]
Moved to #16 .
